flickr_photo_wall/__init__.py
"""The main file, responsible for creating and setting up the flask app"""
from flask import Flask
from flask_socketio import SocketIO

app = Flask(__name__, instance_relative_config=True)
socketio = SocketIO(app)


def setup_app(config="default"):
    """Configure the flask app and return references"""
    configure_cfg(app, config)
    configure_bp(app)
    return app, socketio


def configure_cfg(app, config):
    """Configure flask config files

    Additional conditional config files will be added here as the project grows
    """
    app.config.from_object('config.' + config)


def configure_bp(app):
    """Configure application blueprints

    Additional blueprints will be added here as the project grows
    """
    from flickr_photo_wall.views import search
    app.register_blueprint(search.search_view, url_prefix='/')


if __name__ == '__main__':
    app, socketio = setup_app(config='default')
    socketio.run(app=app, port=8080, host='0.0.0.0', debug=True)

flickr_photo_wall/controllers/flickr_api.py
"""Flickr API Controller"""
import json
import os
import requests
from flask import current_app


class FlickrAPI(object):
    """The FlickrAPI Class"""

    def __init__(self):
        """FlickrAPI constructor"""
        self.search_url = os.path.join(current_app.config['FLICKR_API_URL'],
                                       current_app.config['FLICKR_PHOTOS_URL'])

    def get_images_by_tags(self, tags):
        """Return a list of image urls given some tags"""
        params = {'tags': tags, 'format': 'json', 'nojsoncallback': 1}
        res = requests.get(url=self.search_url, params=params)

        items = json.loads(res.content)['items']
        image_url_list = [item['media']['m'] for item in items]

        return image_url_list

flickr_photo_wall/controllers/search.py
"""Flickr API Controller"""
import json
import os
import requests
from flask import current_app


class FlickrAPI(object):
    """The FlickrAPI Class"""

    def __init__(self):
        """FlickrAPI constructor"""
        self.search_url = os.path.join(current_app.config['FLICKR_API_URL'],
                                       current_app.config['FLICKR_PHOTOS_URL'])

    def get_images_by_tags(self, tags):
        """Return a list of image urls given some tags"""
        params = {'tags': tags, 'format': 'json', 'nojsoncallback': 1}
        res = requests.get(url=self.search_url, params=params)

        items = json.loads(res.content)['items']
        image_url_list = [item['media']['m'] for item in items]

        return image_url_list

flickr_photo_wall/views/search.py
"""flickr_photo_wall search view"""

import flask
from flask import render_template
from flask_socketio import emit

from flickr_photo_wall import socketio
from flickr_photo_wall.controllers.flickr_api import FlickrAPI

search_view = flask.Blueprint(
    'search',
    __name__,
    template_folder='templates',
    static_folder='static')


@search_view.route('/')
def index():
    """The default route for this app"""
    return render_template('index.html')


@socketio.on('search')
def search_listener(request):
    """A socketio listener for incoming search requests"""
    tags = filter(None, request['search'].split(' '))
    flickr = FlickrAPI()
    result = flickr.get_images_by_tags(tags)
    emit('search', result, json=True)

flickr_photo_wall/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

    <!-- Dependencies -->
    <script src="{{ url_for('static', filename='dist/app.js') }}"></script>
    <link href="{{ url_for('static', filename='dist/app.css') }}" rel="stylesheet"/>

</head>
<body>

<ul class="nav nav-tabs bg-dark">
    {% block nav_items_left %}
        <li class="nav-item mr-auto">
            <a class="nav-link py-1 px-3 nav-brand" href="{{ url_for('search.index') }}">
                <span class="text-capitalize">Home</span>
            </a>
        </li>
    {% endblock %}
    {% block nav_items_right %}
 {% endblock %}
</ul>

{% block page_body %}

{% endblock %}
</body>

{% block footer %}
    <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
{% endblock %}

</html>

flickr_photo_wall/templates/index.html
{% extends '_base.html' %}
{% block title %} flickr Image Search {% endblock %}
{% block nav_items_right %}
    {{ super() }}
    <li class="nav-item">
        <a style="display: none" id="redo-href" class="nav-link py-1 px-3" href="#" onclick="newSearch()">
            <span class="oi oi-magnifying-glass"></span>
        </a>
    </li>
    <li class="nav-item">
        <a style="display: none" id="pause-href" class="nav-link py-1 px-3" href="#" onclick="toggleSocketQuery()"
           data-toggle="snackbar" data-content="Slideshow Resumed" data-timeout="1500">
            <span id="pause-icon" class="oi oi-media-pause"></span>
        </a>
    </li>
{% endblock %}

{% block page_body %}
    <div id="search-container" class="container mt-5">
        <div class="row">
            <div class="d-flex col justify-content-center">
                <h1 class="site-header mt-4 mb-0 text-center">
                    <span class="flickr-blue">flick</span><span class="flickr-pink">r</span> Image Search
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="d-flex col justify-content-center">
                <h6 class="text-center d-block">Search public flickr images by specifying tags.
                                            <br> An empty query returns all recent images.
                </h6>
            </div>
        </div>
        <div class="row">
            <div class="d-flex col justify-content-center">
            <span class="bmd-form-group justify-content-center text-center pt-4">
                <input id="search-input" class="form-control form-control-lg form-control-success"
                       placeholder="Search..." autocomplete="off" spellcheck="false" type="search" name="search">

                <button onclick="newQuerySocket()" id="submit" class="btn btn-raised btn-primary my-4 ml-3">Search</button>
            </span>
            </div>
        </div>
    </div>

    <div id="loader-placeholder"></div>

    <div id="result-container" class="container-fluid">
        <div class="row mt-2">
            <div class="col justify-content-center">
                <div class="grid">
                    <div class="gutter-sizer"></div>
                    <div class="grid-sizer"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
{{ super() }}

<script>
let currentImagesHash = {}; // Hashmap to keep track of images that have been processed
let currentImageCount = 0;  // Current count of images that have been processed; 0 <= currentImageCount <= 20
let queryIntervalMS = 3000; // Interval in milliseconds to query socket
let querySocketInterval = null;  // JS Interval representing the function that continuously queries the backend socket
let querySocketIntervalIsRunning = false;  // Is the above interval running?
let currentQuery = null;  // Current set of tags used to query the backend
const socket = io.connect(window.location.protocol + '//' + document.domain + ':' + location.port); // Initialize socketio
const $grid = $('.grid').masonry({ // Initialize masonry
    itemSelector: '.card',
    columnWidth: '.grid-sizer',
    gutter: '.gutter-sizer',
    transitionDuration: '0.8s'
});

/*
* Listener for 'search' messages on the socket.
* Processes data returned from search and draws results to screen
*/
socket.on('search', function(data) {
    processSearchResults(data)
        .then((res) => {
            if (res === true) {
                drawSearchResults();
            }
        });
});

/*
* Create card elements given some data
*/
function processSearchResults(data) {
    return new Promise(function(resolve, reject) {
        let newImagesAdded = false;
        for (let item in data) {
            if (!(data[item] in currentImagesHash)) {
                newImagesAdded = true;

                if (currentImageCount >= 20) {
                    let lastCard = $('.grid .card').last();
                    lastCard.remove();
                } else {
                    currentImageCount++;
                }

                currentImagesHash[data[item]] = true;

                let image = $('<img>');
                image.attr('src', data[item]);
                image.addClass('flickr-img card-img-top');

                let card = $('<div></div>');

                card.addClass('flickr-img card')
                    .append(image);

                $grid.prepend(card)
                    .masonry('prepended', card)
                    .masonry('reloadItems')
                    .masonry('layout');
            }
        }
        resolve(newImagesAdded);
    });
}

/*
* Start a new search query against the backend.
* Draws a loader to the frontend and sets the current tag query.
*/
function newQuerySocket() {
    drawSearchLoading();
    currentQuery = $('input[name="search"]').val();
    startSocketQuery();
}

/*
* Emit a "search" message to the backend, effectively requesting new search results.
*/
function startSocketQuery() {
    socket.emit('search', {search: currentQuery});
    querySocketInterval = setInterval(() => {
        socket.emit('search', {search: currentQuery});
    }, queryIntervalMS);
    querySocketIntervalIsRunning = true;
}

/*
* Stop querying the backend by clearing the current Interval responsible for querying
*/
function stopSocketQuery() {
    clearInterval(querySocketInterval);
    querySocketIntervalIsRunning = false;
}

/*
* Toggle the Interval responsible for querying and change the frontend media controls to reflect the current state
*/
function toggleSocketQuery() {
    if (querySocketIntervalIsRunning) {
        setMediaControlsPaused();
        stopSocketQuery();
    } else {
        setMediaControlsPlaying();
        startSocketQuery();
    }
}

/*
* Set the frontend mediacontrols and snackbar message to be paused.
*/
function setMediaControlsPaused() {
    $('#pause-href').attr('data-content', 'Slideshow Paused');

    let toggleIcon = $('#pause-icon');
    toggleIcon.removeClass('oi-media-pause');
    toggleIcon.addClass('oi-media-play');
}

/*
* Set the frontend mediacontrols and snackbar message to be resumed.
*/
function setMediaControlsPlaying() {
    $('#pause-href').attr('data-content', 'Slideshow Resumed');

    let toggleIcon = $('#pause-icon');
    toggleIcon.removeClass('oi-media-play');
    toggleIcon.addClass('oi-media-pause');
}

/*
* Render the loading screen
*/
function drawSearchLoading() {
    $('#search-container').hide();
    $('#loader-placeholder').addClass('loader');
}

/*
* Render the search results
*/
function drawSearchResults() {
    $('#result-container').show();
    $('#loader-placeholder').removeClass('loader');
    $('#pause-href').show();
    $('#redo-href').show();
    $grid.masonry('layout').masonry('reloadItems');
}

/*
* Render the default search view
*/
function drawSearch() {
    $('#search-container').show();
    $('#result-container').hide();
    $('#pause-href').hide();
    $('#redo-href').hide();
}

/*
* Reset the state of the application and redraw as if the page had been refreshed.
*/
function newSearch() {
    stopSocketQuery();
    currentImagesHash = {};
    currentImageCount = 0;
    setMediaControlsPlaying();
    drawSearch();
    $('#result-container .grid .card').remove();
}
</script>
{% endblock %}